version: '3'

services:
  portainer:
    image: portainer/portainer-ce:2.16.1-alpine
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports:
      - 8000:8000
      - 9443:9443

volumes:
  portainer-data: